server:
  port: 8888

spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config,classpath:/config